pkgs:
[
  pkgs.awscli2
  pkgs.cargo
  pkgs.chafa
  pkgs.clang
  pkgs.direnv
  pkgs.duckdb
  pkgs.eternal-terminal
  pkgs.fd
  pkgs.fzf
  pkgs.git-lfs
  pkgs.htop
  pkgs.jq
  pkgs.jupyter
  pkgs.k9s
  pkgs.kubectx
  pkgs.kubernetes-helm
  pkgs.kustomize
  pkgs.lazydocker
  pkgs.lazygit
  pkgs.lazysql
  pkgs.lua5_1
  pkgs.luarocks
  pkgs.mosh
  pkgs.mutt
  pkgs.neovim
  pkgs.nodePackages.cspell
  pkgs.nodejs
  pkgs.openblas
  pkgs.opencommit
  pkgs.packer
  pkgs.poetry
  pkgs.python3Packages.pynvim
  pkgs.quarto
  pkgs.rclone
  pkgs.restic
  pkgs.ripgrep
  pkgs.ripgrep-all
  pkgs.ruff
  pkgs.rust-analyzer
  pkgs.rustc
  pkgs.tailscale
  pkgs.tenv
  pkgs.tmux
  pkgs.tree-sitter
  pkgs.ueberzugpp
  pkgs.uv
  pkgs.viu
  pkgs.wget
  pkgs.yq
]
